export const FETCH_MOVIES = 'FETCH_MOVIES'
export const FETCH_TV_SHOWS='FETCH_TV_SHOWS'
export const CHANGE_URL = 'CHANGE_URL'
export const SET_TAB = 'SET_TAB'
export const SET_SEARCH_BAR = 'SET_SEARCH_BAR'
export const FETCH_MOVIE_DETAILS='FETCH_MOVIE_DETAILS'
export const FETCH_VIDEOS='FETCH_VIDEOS'

